### ISSUE TITLE
Chat room

### ISSUE THREAD

**Issue by MadcapJake** [pyos/dg#10]
Are you intending or is anyone interested in setting up a chat room in IRC, gitter, xmpp or wherever?

**Comment by pyos** [comment]
Nah, why would anyone need one? It's not like anyone is *actually* using this.

**Comment by MadcapJake** [comment]
Well, if anyone is interested, I'll be lurking in #dogelang on IRC.

**Comment by LeaveNhA** [comment]
Why not creating a Twitter List?
