### ISSUE TITLE
Make true, false, and none equal their capital letter equivalant.

### ISSUE THREAD

**Issue by XiKuuKy** [pyos/dg#14]
I thought it would be cool if true, false, and none were all the same as True, False, and None. I doubt that this will get implemented. Good work guys!

**Comment by pyos** [comment]
I don't know, `True` and `true` aren't that different anyway, and neither actually follows the naming convention for constants (which is all-caps). There are lots of other violations in the Python stdlib, too, like `str`, `int`, `type`, etc. which should be `Str`, `Int`, `Type`...changing that now is kinda pointless.

Thanks for the kind words, though.
