### ISSUE TITLE
Feature suggestion: import *

### ISSUE THREAD

**Issue by kirbyfan64** [pyos/dg#19]
Ok, this time I *swear* I read the tutorial section on imports at least 10 times in a row. So, either this doesn't exist, or it isn't documented.

Basically, I'm looking for the `dg` equivalent of `from x import *`. The only thing I can think of is `locals!.update (import '/x' pure |>.__dict__)`...which isn't that nice.

My idea is just `import '/x/*'`; the suffix `*` would mean "import the module's contents". I have an implementation idea (`from x import *` seems to basically be `import x`, except with the `STORE_NAME` replaced with `IMPORT_STAR` and changing the `None` constant to `('*',)`).

**Comment by pyos** [comment]
Isn't `from x import *` considered bad practice though?

**Comment by kirbyfan64** [comment]
Well, kind of...

But I often write simple utility modules for my packages that contain really basic stuff like:

```
lmap = (list) <- (map)
isnot = (not) <- (is)

MyException = subclass Exception where
  # ...
```

And it's kind of annoying to have to do stuff like `util.isnot` vs. just `isnot`.
