### ISSUE TITLE
Newline pipes ?

### ISSUE THREAD

**Issue by vindarel** [pyos/dg#20]
Hi,
big fan here. No, just kidding.
Is it possible to write a pipe at a newline ? 
Something like

```coffeescript
"foo" 
|> upper!
```
But yeah as usual, who would want to use this ?

btw, is there any more features you plan to add ?

Regards

**Comment by pyos** [comment]
Nope, not possible. Line breaks are infix operators with *really* low precedence, and `a R Q b` where R has lower precedence than Q is parsed as `a R (Q b)`. (Like `a R b Q c` <=> `a R (b Q c)`, but without the nonterminal in the middle.)

>is there any more features you plan to add ?

Probably not. Kinda busy with other stuff.
