### ISSUE TITLE
How do you do syntax highlighting ?

### ISSUE THREAD

**Issue by vindarel** [pyos/dg#21]
Hi,
In your markdown tutorial your code snippets are surrounded by

```
 ```dg
```
and dg code is well highlighted. I tried the same for a github readme, with no success. What's the engine that knows dg ?

**Comment by pyos** [comment]
That's [Pygments](http://pygments.org/). Github used to use it, too, but then they switched over to something written in Ruby, losing support for quite a few languages in the process.

**Comment by vindarel** [comment]
ok thanks. I had checked it out, but they need to update their list of supported languages then http://pygments.org/languages/.

**Comment by pyos** [comment]
Yeah, should probably update the lexer itself as well...IIRC, it highlights brackets (`{}[]`) as errors.
