### ISSUE TITLE
Consider replacing async $ with some arrow

### ISSUE THREAD

**Issue by iamale** [pyos/dg#22]
Async functions are vital in some-modern-shiny-framework-based apps (i. e. [Kyoukai][kyo]). So it would be awesome to write something like
```
route "/" $ ctx ->> "Hello world!"
```
instead of
```
route "/" $ async $ ctx -> "Hello world!"
```

[kyo]: https://mirai.veriny.tf/

Micro-PR here:
```
Compiler.prefix !! '->>' = f (args, body) ~> @pushfunc True args body
```

**Comment by pyos** [comment]
Good idea. Never liked marking function with `asyncio.coroutine` in 3.4, and while `async` is an improvement, it's still a bit annoying.

**Comment by iamale** [comment]
(Oh, and `~>>` could be useful at some point, too! _slowpoke.jpg_)

**Comment by pyos** [comment]
TBH `~>` was probably a mistake. It leads to some confusing behavior, such as `__init__ = ~> ...` being invalid.

**Comment by iamale** [comment]
I think that the property part is misleading, but apart from that it's OK. But maybe it can be replaced with a more transparent syntax like
```
@, eggs -> @.spam eggs    # just make @ a valid identifier?
@, eggs -> @spam eggs     # or some sort of transitional syntax
self, eggs -> @spam eggs  # fine too
```

**Comment by jamesguessis** [comment]
Sorry to comment on such an old _closed_ issue, but will ~>> never be a thing?

**Comment by XertroV** [comment]
@jamesguessis - can't you monkey patch the compiler with OPs micro PR? From memory that's possible.

**Comment by pyos** [comment]
There's actually a few more places where you need to add the operator in order to have complete support...either way, done. (If you're using something other than CPython 3.7, it will take two startups or a manual `python -m dg -b` to rebuild the bundle due to a deficiency in the automatic rebuild process.)
