### ISSUE TITLE
Basic syntax

### ISSUE THREAD

**Issue by fuzzthink** [pyos/dg#26]
What is the syntax for:
`import a as b`
`from x import y, z`
`x = [i for i in range(3)]`

**Comment by kirbyfan64** [comment]
- `import a as b` -> `b = import '/a' pure`
- `from x import y, z` -> I don't think there's really much of an equivalent to this...
- `x = [i for i in range(3)]` -> Pretty much any list comprehensions can be replaced with maps (e.g. `map (i -> i) $ range 3`), though in this case, you can of course just do `list $ range 3`.

**Comment by fuzzthink** [comment]
Thank you.

How is a list indexed?, eg. `a = [0, 1]`
`a[0]`

**Comment by pyos** [comment]
If you prefer generator comprehensions to higher-order functions, you can also do this:
```dg
list (where for i in range 3 => yield i)
```
Technically, this is not a comprehension, but an anonymous function that happens to be a generator because it contains a `yield` and is called in-place because it was created with `where`. So this syntax is actually more powerful than comprehensions in Python because you can replace the `for` loop with absolutely anything. For example, to create a list of 4K blocks read from a file:
```dg
list (where with fd = open 'name' => while chunk = fd.read 4096 => yield chunk)
```

>How is a list indexed?

`a !! 0`, like in Haskell.

**Comment by fuzzthink** [comment]
Thank you, that is helpful.
How about syntax for list slices?

**Comment by pyos** [comment]
Uh, well, there were some attempts to add one, but they never went anywhere, so for now it's `xs !! slice start stop [step]` (same as `xs[slice(start, stop[, step])]` in Python).

**Comment by fuzzthink** [comment]
In python, a method can create a new instance of its own class:
```
class Node:
  ...
  def addChild(self, item):
    node = Node(item) 
    ...
```
In dg, if I do:
`node = Node item`
it errors saying Node is not something one can assign to. How can I do this in dg?
thanks.

**Comment by kirbyfan64** [comment]
@fuzzthink It should work. Can you show the dg version you wrote of `Node`?

**Comment by fuzzthink** [comment]
Ok, reducing the code to bare minimum seems to work, but getting a different kind of error.
```
Node = subclass object where
  __init__ = i ~>
    @childs = []
    @i = i
    None

  addChild = i ~>
    @childs.append $ Node i

n = Node 1
n.addChild 2
print $ len n.childs  # 1
print n.childs!!0
# TypeError: 'NoneType' object is not subscriptable
```

**Comment by kirbyfan64** [comment]
```
print n.childs!!0
```

`!!` has lower precedence than calling. Try `print $ n.childs !! 0`.

**Comment by fuzzthink** [comment]
Hmm, I think this should be considered a bug then. In python, the index operator is the 2nd highest precedence, along with the `.`; only the grouping operator is higher. In haskell, it is similarly as high.

**Comment by pyos** [comment]
Function call is an operator, too. Here's how Haskell parses this sort of thing:

```haskell
λ let f x = [x] in f 1 !! 0
1
```

**Comment by fuzzthink** [comment]
How do you do multiple string interpolations?
```
"%i %i" % (1, 2)
```
didn't work.

**Comment by kirbyfan64** [comment]
> And is there a way to print multiple var/expressions without string interpolation?

```python
print 1, 2
```

dg is still Python, so `print` is the same as Python's `print`.

**Comment by fuzzthink** [comment]
Not really,
py3>:
```
print('hi', 1, 2)
hi 1 2
```

dg>:
```
print 'hi', 1, 2
hi
(None, 1, 2)
```

So to get the same output as python, is string interpolation the way? What is the syntax for more than 1 variable?

**Comment by pyos** [comment]
```
print 1 2
print $ "%d %d" % (1, 2)
print $ "{} {}'.format 1 2
```

Arguments are separated by spaces.

**Comment by fuzzthink** [comment]
Ah, my bad for forgetting no commas and missing $, thanks.

**Comment by fuzzthink** [comment]
```
childs.sort (c1 c2 -> c1.visits - c2.visits)
```
TypeError: must use keyword argument for key function

Am I doing something wrong?

**Comment by pyos** [comment]
You'll probably want to read this: https://docs.python.org/3/howto/sorting.html#key-functions

**Comment by fuzzthink** [comment]
Thank you.
