### ISSUE TITLE
variable leakage?

### ISSUE THREAD

**Issue by fuzzthink** [pyos/dg#27]
`a = list $ (map (_ -> _) $ range 3)`
`_ # 2`
`_` should be undefined outside of the function, no?

**Comment by fuzzthink** [comment]
Ok, I guess I was kind of wrong, first line above didn't even work unless `_` is defined. But if use something else, like `i`, it would work. `_` seems special in dg? Eg.

```
a = list $ (map (_ -> _) $ range 3) # NameError: name '_' is not defined
a = list $ (map (i -> i) $ range 3) # OK
i  # not defined (good)
_  # [0, 1, 2]  (not good, _ should not be defined..)
```

**Comment by pyos** [comment]
In the REPL, `_` is the result of the previous statement. (This is default Python REPL behavior implemented in `sys.displayhook`.) The result of an assigment to `a` is `a`.

Like in Haskell, `_` is a placeholder meaning "ignore this value" when used in assignments and function arguments.
