### ISSUE TITLE
Calling dg from CPython 3.6

### ISSUE THREAD

**Issue by justuswilhelm** [pyos/dg#29]
Is there any possibility of loading dg code objects in a regular CPython program? A use case would be
slowly migrating a code base to dg. Interop is always a great sales proposition. Perhaps this could work similarly to how hylang registers an import hook.

If this is something I could help out with, please let me know. I'm very excited about finding this project.

**Comment by pyos** [comment]
It comes with an import hook, so you can `import dg` and then import modules written it and use them just like normal Python modules. Did I forget to mention that in the tutorial?...I guess I did.

(That's assuming it still works on CPython 3.6. AFAIK there was another beta release, so the bytecode format might have changed.)

**Comment by justuswilhelm** [comment]
Great! It works! Now, off to trying to use this in production code... I suppose this issue should be "Document import hook".

**Comment by shizhaojingszj** [comment]
+1 @pyos please add this to doc.

**Comment by pyos** [comment]
Added to the usage section of the tutorial, thanks for reminding me.
