### ISSUE TITLE
Lambdas

### ISSUE THREAD

**Issue by rickyhan** [pyos/dg#31]
Just looked at the doc. Does it have any lambda functions? Also are monadic expression supported?

**Comment by vindarel** [comment]
Hi, you might want to see the "creating functions" part on https://pyos.github.io/dg/tutorial/. Some examples:

```
# Arguments can have default values.
# Anything that is valid to the left of = is also valid as an argument name.
snd = (whole_tuple = (a, b)) -> b
snd (1, 2) #=> 2

# no arguments
useless_function = -> print "Really useless."
```
