### ISSUE TITLE
PyPy3 support

### ISSUE THREAD

**Issue by auscompgeek** [pyos/dg#32]
PyPy3 supports Python 3.5 now…

**Comment by pyos** [comment]
Done. `pypy3-c -m dg -b` appears to be ~3 times slower than CPython 3.6, though, so I don't know if there was any point in doing this.

**Comment by kirbyfan64** [comment]
FWIW PyPy has a longer startup time but will generally be faster for really long-running programs (e.g. [this](https://morepypy.blogspot.com/2017/03/async-http-benchmarks-on-pypy3.html)).
