### ISSUE TITLE
Can I have `eval` for dg?

### ISSUE THREAD

**Issue by w3rs** [pyos/dg#33]
It seems like `eval` is from Python:

>>> eval 'print 2'
Traceback (most recent call last):
  File "/home/alex/w/meanings/dg/repl.dg", line 106, in runrepl
    v = eval x module.__dict__
  File "<input>", line 1, in 
  File "<string>", line 1
    print 2
          ^
SyntaxError: Missing parentheses in call to 'print'

Is there a way to eval string with dg code, from either Python or dg?

**Comment by vindarel** [comment]
Hi there, 
it seems to me that we'd use a combination of `parse` and python's `eval`:

    import '/dg/parse'
    import '/dg/compileast'
    tree = parse cmd
    res = eval $ compileast tree, sys.modules

I tried something like this for a prompt-toolkit integration: https://gitlab.com/vindarel/ptdg (it's clunky). I'd look at [the dg repl](https://github.com/pyos/dg/blob/master/repl.dg).

**Comment by pyos** [comment]
Yeah, the compiled object is just a [types.CodeType](https://docs.python.org/3.6/library/types.html#types.CodeType), you can pass those to `eval`. (Also note that `dg.compileast (dg.parse cmd)` is the same as `dg.compile cmd`.

```
>>> eval $ dg.compile '1 + 1'
2
```

(BTW, there's also a built-in function ["compile"](https://docs.python.org/3.6/library/functions.html#compile) that compiles Python code to `CodeType` objects. It even has a mode that allows compiling statements, so `eval(compile("for x in range(3): print(x)", "<string>", "exec"))` works even though `eval("for x in range(3): print(x)")` doesn't.)

**Comment by w3rs** [comment]
Nice, thanks!
