### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ceremcem** [pyos/dg#35]
Is it?

**Comment by pyos** [comment]
Depends on your definition of "dead", I guess.

**Comment by vindarel** [comment]
Last commit on may of this year and project on par with Python 3.5… come on, no time to worry.

**Comment by ceremcem** [comment]
Okay, good to know you are there :)

The problem is that when I didn't find any information about "dgprocedures", I started worrying. Also, there is a bug report (#30) left without any interaction (no labels, no comments, nothing) that made me start thinking about if this project is dead or alive.

**Comment by krnak** [comment]
Are you going to return to this project @pyos ?

It's a brilliant toy (: but I see last commit on Jun 14, 2020 and python > 3.7 is still not supported :/

**Comment by LeaveNhA** [comment]
> It's a brilliant toy (: but I see last commit on Jun 14, 2020 and python > 3.7 is still not supported :/

🥲

@pyos, alive bro?

**Comment by pyos** [comment]
No

**Comment by LeaveNhA** [comment]
@pyos. Won't you continue or won't you let us (or me) continue to this language?

**Comment by pyos** [comment]
>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software [...]

¯\\\_(ツ)\_/¯
