### ISSUE TITLE
How are we supposed to debug an application?

### ISSUE THREAD

**Issue by ceremcem** [pyos/dg#36]
This project is much like Livescript and Livescript provides sourcemaps, thus allowing breakpoints, variable inspection etc. in a visual IDE.

How are we supposed to benefit such debugging techniques in dg?

**Comment by kirbyfan64** [comment]
AFAIK Python's pdb should work just fine, as well as any other Python debugging tool.

**Comment by vindarel** [comment]
this works:

    import '/ipdb'
    ipdb.set_trace!

and `dg myscript.dg` breaks into the debugger.

**Comment by ceremcem** [comment]
Hmm. `ipdb` shows the original code as I needed. Thank you.

**Comment by ceremcem** [comment]
@kirbyfan64 `pdb` shows the original code as well, but it requires pressing `l` every time we evaluate `n(ext)` line, which makes it very annoying, IMHO.
