### ISSUE TITLE
Supplying bytecode without sources

### ISSUE THREAD

**Issue by velavokr** [pyos/dg#5]
Hoped to read the sources but found only a couple of binary blobs. :(
Anyway, I'm impressed.

**Comment by pyos** [comment]
The sources these blobs are generated from are in /core/; the compiler is written in dg itself, so the blobs are necessary to bootstrap it (which can be done by running `python3 -m dg -b`).

**Comment by velavokr** [comment]
Just made sure. Will play with the thing when I get some free time.
