### ISSUE TITLE
Feature request: Double colon function exectution

### ISSUE THREAD

**Issue by m1sta** [pyos/dg#50]
DSLs are useful. It'd be nice to have some sugar for them. Using a function name followed by a Double colon will pass the next block as a string when invoking the function 

```

SQL = query -> # do stuff

result = SQL ::
    Select * from table


```

**Comment by pyos** [comment]
IMO this isn't particularly useful because

1. there's not a big difference between this and just using a raw multi-line string;
2. it'll confuse syntax highlighters that don't happen to support your particular DSL.

**Comment by m1sta** [comment]
I guess being able to invoke functions without parents makes this basically possible already?
