### ISSUE TITLE
such happy .. wow

### ISSUE THREAD

**Issue by burdges** [pyos/dg#8]
I just wanted to say :  I love Haskell. And I love Doge.  And I know far too many people who use Python more than in probably ideal.  So dg makes me very happy.  :)

**Comment by burdges** [comment]
But maybe you'll want a twitter or something so that idiots don't feel the need to post such useless issues.  ;)

**Comment by pyos** [comment]
>dg makes me very happy. :)

![](http://i.imgur.com/rQ9o7MG.png)

That's not a bug, though.
